### ISSUE TITLE
Conflict with bbPress

### ISSUE THREAD

**Issue by grantpalin** [justintadlock/custom-header-extended#1]
I've got a site in dev where bbPress was not functioning. Having disabled all plugins and reactivated them one by one, having this plugin active alongside bbPress causes functionality of the latter to fail.

Specifically: can't create topics or forums via the top menu - receive a message about invalid post type. Also, bbPress settings or Topics or Forums are not listed on the backend.

WordPress v3.8
bbPress 2.5.2
Custom Header Extended 0.1.0

**Comment by justintadlock** [comment]
Closing this as it's out of date now and haven't been able to reproduce.  Feel free to reopen if needed.
