### ISSUE TITLE
Wp Types support

### ISSUE THREAD

**Issue by Colir** [justintadlock/custom-header-extended#2]
Hi,
It will be really great if your plugin can work with Types plugin and the custom post type that it generate.
thansk a lot

**Comment by justintadlock** [comment]
Can you post the names of the post types?  Or, link to the plugin so I can see what post types it registers?  I'll consider them.

**Comment by Colir** [comment]
Hi.
here is the plugin https://wordpress.org/plugins/types/
In my dev, my post-type name is "headline"

Thanks

**Comment by justintadlock** [comment]
Closing this one.  WP Types should actually add in support for this plugin.  When creating a new post type, it should give you an option to add in support for `'custom-header'`.  Because WP Types allows you to create arbitrary post types, the support needs to be added from their end.

**Comment by justintadlock** [comment]
Also, sorry for the long wait on this.  I overlooked this ticket.
